# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Yao同學
subtitle: To Be Better!
author: Yao同學
language: zh_CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://int64.icu/
root: /
#permalink: :year/:month/:day/:title/
permalink: :category/:title/
permalink_defaults:
  lang: en

#Custom Setting Start

# Site settings
SEOTitle: Yao同學 | Blog
email: aiup1995@163.com
description: ""
keyword: ""
header-img: https://www.wallpaperup.com/uploads/wallpapers/2017/07/09/1094258/00fac2df3e68ab928d9d19d3e1972c88.jpg
article-img: /img/article_header/article_bg.jpg
404-img: /img/header_img/404.jpg
signature: false #show signature
signature-img: img/signature/BeanTechSign-white.png 


# SNS settings
# RSS: false
weibo_username:     aiupni
# zhihu_username:     Demonbane
github_username:    cheerduo
# twitter_username:   Demonbane_x
#facebook_username:  YenYuHsuan
#linkedin_username:  huweihuang

# Build settings
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`


# Disqus settings
#disqus_username: your-disqus-ID

# Duoshuo settings
# duoshuo_username: kaijun
# Share component is depend on Comment so we can NOT use share only.
#duoshuo_share: true                     # set to false if you want to use Comment without Sharing


# Analytics settings
#Baidu Analytics
#ba_track_id: r45fhy7653897235wg5ye709d930f62e
# Google Analytics
#ga_track_id: 'UA-XXXXXXXX-X'          # Format: UA-xxxxxx-xx
ga_domain: yoursite


# Sidebar settings
sidebar: true                       # whether or not using Sidebar.
sidebar-about-description: "The shortest answer is doing!"
sidebar-avatar: /img/avatar/lover.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`
widgets:
- featured-tags
- short-about
- recent-posts
#- friends-blog
- archive
#- category

# widget behavior
## Archive
archives-img: /img/header_img/archives-widget.jpg
archive_type: 'monthly'
show_count: true


## 已有标签
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 0              # A tag will be featured if the size of it is more than this condition value


## Friends
# friends: [
    # {
        # title: "CSDN Blog 胡伟煌",
        # href: "http://blog.csdn.net/huwh_"
    # }
# ]


#Custom Setting End



# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: article
category_map:
  Docker: docker
  Kubernetes: kubernetes
  Golang: golang
  Nginx: nginx
  Etcd: etcd
  Database: database

tag_map:
home_posts_tag: true # show posts tags

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: archives

archive_generator:
  per_page: 10
  yearly: true
  monthly: true
  daily: false
  
# Markdown-it config
## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
    quotes: '“”‘’'
  
# Extensions
## Plugins: https://hexo.io/plugins/

# recommended-posts
# reference: https://github.com/huiwang/hexo-recommended-posts
# recommended_posts:
#   server: https://api.truelaurel.com #后端推荐服务器地址
#   timeoutInMillis: 10000 #服务时长，超过此时长，则使用离线推荐模式
#   internalLinks: 3 #内部文章数量
#   externalLinks: 0 #外部文章数量
#   autoDisplay: true, #自动在文章底部显示推荐文章
#   titleHtml: <h2>推荐文章<span style="font-size:0.45em; color:gray"></span></h2> #自定义标题

# hexo-tag-aplayer
# reference: https://github.com/MoePlayer/hexo-tag-aplayer
# aplayer:
#   meting: true

## Themes: https://hexo.io/themes/
theme: A-Boy

#sitemap
sitemap:
  path: sitemap.xml

# Deployment
## Docs: https://hexo.io/docs/deployment.html
# repository: https://github.com/huweihuang/xxxxxxx.github.io.git
# branch: master
deploy:
  type: git
  repository: https://github.com/cheerduo/cheerduo.github.io.git
  branch: master
  message: Update ALL
